name: Check Style

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  style:
    name: style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run shared style check
        uses: Burki24/Symcon_ModuleCI/style@v1.0.0
